<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Correspondence                  (0)</name>
   <tag></tag>
   <elementGuidId>6951b036-a809-4869-842b-1873e74b6bae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mount-bidding']/div/div/div[3]/div/div/nav/div/div[4]/div/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_tabs_tabs__link__Xw6wH_QHByb</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Correspondence
                  (0)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mount-bidding&quot;)/div[@class=&quot;_detail_page_l-detail-page__2uEJ4_QHByb&quot;]/div[@class=&quot;_detail_page_l-detail-page__main__3Mc5p_QHByb&quot;]/div[@class=&quot;_detail_page_l-detail-page__subtabs__kbfMs_QHByb&quot;]/div[@class=&quot;_tool_header_l-tool-header__1dofI_QHByb&quot;]/div[@class=&quot;_tool_header_l-tool-header__tabs__3H1tE_QHByb&quot;]/nav[@class=&quot;_tabs_tabs__NUfQA_QHByb&quot;]/div[@class=&quot;_tabs_tabs__list__1aCdZ_QHByb&quot;]/div[@class=&quot;_tabs_tabs__tab__3EPhF_QHByb&quot;]/div[1]/a[1]/span[@class=&quot;_tabs_tabs__link__Xw6wH_QHByb&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mount-bidding']/div/div/div[3]/div/div/nav/div/div[4]/div/a/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bidders (0)'])[1]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Files'])[1]/following::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Log (0)'])[1]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change History (1)'])[1]/preceding::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a/span</value>
   </webElementXpaths>
</WebElementEntity>
