<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input___input_input__2nVpu_QHByb search-bar_82ecf1</name>
   <tag></tag>
   <elementGuidId>48c18d7a-31bf-48d6-947e-22f08a77fff5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_input_input__2nVpu_QHByb search-bar_search-bar__container__search__3Fl93</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search this Project</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-id</name>
      <type>Main</type>
      <value>navbar-global-search-input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;bid_packages-scope&quot;]/div[@class=&quot;_portal_portal__BR8hE_QHByb&quot;]/div[@class=&quot;results-page_results-page__scrim__84JvE results-page_results-page__scrim--fade-in__3fLuK&quot;]/div[1]/div[@class=&quot;_list_page_l-list-page__jY1zk_QHByb results-page_results-page__tg5_V results-page_results-page--medium__qM-uT&quot;]/div[@class=&quot;_list_page_l-list-page__main__9kCei_QHByb results-page_results-page__main__2ljwZ&quot;]/div[@class=&quot;_flex_flex-align-items-flex-start__2gWD7_QHByb _flex_flex-justify-content-flex-start__VAZ4J_QHByb _flex_flex-row__T2BDx_QHByb results-page_results-page__container__171uo&quot;]/div[@class=&quot;_flex_flex-align-items-center__tNXXc_QHByb _flex_flex-justify-content-flex-start__VAZ4J_QHByb _flex_flex-column__1RR_i_QHByb results-page_results-page__middle-column___hXVc&quot;]/div[@class=&quot;_flex_flex-align-items-center__tNXXc_QHByb _flex_flex-justify-content-flex-start__VAZ4J_QHByb _flex_flex-column__1RR_i_QHByb results-page_results-page__middle-column__max-sizer__2rE6I&quot;]/div[@class=&quot;search-bar_search-bar__container__bHSJ1 search-bar_search-bar__container--grow__Ci5qR&quot;]/div[@class=&quot;_input_icon-layout__1AtMT_QHByb _input_icon-layout--count-1__cH8_J_QHByb&quot;]/input[@class=&quot;_input_input__2nVpu_QHByb search-bar_search-bar__container__search__3Fl93&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
   </webElementXpaths>
</WebElementEntity>
