<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Commitment Summary_caret</name>
   <tag></tag>
   <elementGuidId>01d2c6da-5550-4ece-a2ff-f03fdd10cb09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main_panel']/div[2]/div/div/div/div[3]/aside/div/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.caret</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>caret</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_panel&quot;)/div[@class=&quot;tool-body print-shrink-to-fit&quot;]/div[@class=&quot;tool-header-container feature-toggle&quot;]/div[@class=&quot;tool-header feature-toggle&quot;]/div[@class=&quot;tool-header-bottom&quot;]/div[@class=&quot;export-container&quot;]/aside[@class=&quot;no_print&quot;]/div[@class=&quot;dropdown-container&quot;]/div[@class=&quot;dropdown open active&quot;]/div[@class=&quot;dropdown-toggle export&quot;]/span[@class=&quot;caret&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main_panel']/div[2]/div/div/div/div[3]/aside/div/div/div/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div/div/div/span</value>
   </webElementXpaths>
</WebElementEntity>
