<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Confirm_fa fa-ellipsis-v viewer_infoIcon__2NP3k</name>
   <tag></tag>
   <elementGuidId>e4c7e72b-9c34-499c-b439-e05a4f95f220</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='photo-props']/div/div/div[7]/div/div[5]/div/div[3]/span/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-ellipsis-v viewer_infoIcon__2NP3k</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;photo-props&quot;)/div[@class=&quot;_1npcp-7_2_5 shared_wrapper__1g_LN&quot;]/div[@class=&quot;tuHQH-7_2_5&quot;]/div[@class=&quot;_1v7oA-7_2_5 _1PmO_-7_2_5 shared_mainContainer__3u_ba&quot;]/div[@class=&quot;modal-window lightbox_lightbox__3AtAc lightbox_visible__2wib_&quot;]/div[@class=&quot;viewer_imageContainer__3RuZT&quot;]/div[@class=&quot;viewer_header__3KF_y&quot;]/div[@class=&quot;viewer_col__2hNtc viewer_lastCol__2pX1e&quot;]/span[@class=&quot;viewer_moreOptionsContainer__1mYcO&quot;]/i[@class=&quot;fa fa-ellipsis-v viewer_infoIcon__2NP3k&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='photo-props']/div/div/div[7]/div/div[5]/div/div[3]/span/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/i</value>
   </webElementXpaths>
</WebElementEntity>
