<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_A002</name>
   <tag></tag>
   <elementGuidId>50378946-883b-49d4-ac06-8424fb9c309a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='drawing-log-root']/div/div/div[2]/div/div[2]/div/div/div/div[2]/div/div[2]/div[2]/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fullscreen-drawing-viewer DrawingLog_table-display-cell__17-su</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/428808/project/drawing_areas/249111/drawing_log/view_fullscreen/98725432?return_action=list&amp;filter_drawing_set=current_set&amp;page=1&amp;page_size=150&amp;total=17&amp;search_string=</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fullscreen-href</name>
      <type>Main</type>
      <value>/428808/project/drawing_areas/249111/drawing_log/view_fullscreen/98725432?return_action=list&amp;filter_drawing_set=current_set&amp;page=1&amp;page_size=150&amp;total=17&amp;search_string=</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>A002</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drawing-log-root&quot;)/div[@class=&quot;DrawingLog_content-container__3hPey&quot;]/div[@class=&quot;container__src-ListPartial__a54Oa&quot;]/div[@class=&quot;Spinner_asyncLoad&quot;]/div[@class=&quot;Spinner_asyncLoadFadeContainer&quot;]/div[@class=&quot;loadedRow__src-ListPartial__260t8&quot;]/div[1]/div[1]/div[@class=&quot;contentContainer__src-Table__3L5K0 tableOverrides_contentContainer__1cgSx showSidebar__src-Table__2ZyGP&quot;]/div[@class=&quot;tableContainer__src-Table__1V654 tableOverrides_tableContainer__2_jcC&quot;]/div[1]/div[@class=&quot;tableBody__src-Table__PC0EN&quot;]/div[@class=&quot;tableRow__src-Table__1GzYi tableOverrides_tableRow__uW7Ut firstDraggable__src-Table__2JstL bodyRowHover__src-Table__8nvr-&quot;]/div[@class=&quot;tableCell__src-Table__QnDkh tableOverrides_tableCell__cmTd6&quot;]/a[@class=&quot;fullscreen-drawing-viewer DrawingLog_table-display-cell__17-su&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawing-log-root']/div/div/div[2]/div/div[2]/div/div/div/div[2]/div/div[2]/div[2]/div[3]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'A002')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Info'])[1]/following::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COVER SHEET'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IFC'])[1]/preceding::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='A002']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/428808/project/drawing_areas/249111/drawing_log/view_fullscreen/98725432?return_action=list&amp;filter_drawing_set=current_set&amp;page=1&amp;page_size=150&amp;total=17&amp;search_string=')])[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
   </webElementXpaths>
</WebElementEntity>
