<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add Filter_collapsible_module collapse_b58f0c</name>
   <tag></tag>
   <elementGuidId>6de9071a-6be8-406c-afb7-2ef3f6654072</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='680288c307f1']/div/article/div[2]/div/div/section/section/div/h2/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>collapsible_module collapsed black-icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;680288c307f1&quot;)/div[1]/article[@class=&quot;fitlterable-table&quot;]/div[@class=&quot;async-load&quot;]/div[@class=&quot;async-load-fade-container&quot;]/div[1]/section[1]/section[@class=&quot;meeting-row&quot;]/div[@class=&quot;table-header&quot;]/h2[@class=&quot;padded-children collapsible-target clickable&quot;]/span[@class=&quot;collapsible_module collapsed black-icon&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='680288c307f1']/div/article/div[2]/div/div/section/section/div/h2/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/span</value>
   </webElementXpaths>
</WebElementEntity>
